CREATE DATABASE IF NOT EXISTS empresa;
USE empresa;
CREATE TABLE IF NOT EXISTS carros(
id_carro INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
marca VARCHAR(100),
placa INT(100)
);

ALTER TABLE carros
MODIFY COLUMN placa CHAR(7);

SELECT * FROM carros;
