CREATE DATABASE IF NOT EXISTS teste_tipo_dados;
USE teste_tipo_dados;

CREATE TABLE IF NOT EXISTS LOCAL_MUNDO(
PAIS_SIGLA CHAR(3) NOT NULL,
estado_nome VARCHAR(100) NOT NULL,
cidade MEDIUMTEXT NOT NULL
);